insulin = "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN"
for aa in "ACDEFGHIKLMNPQRSTVWY":
    number = insulin.count(aa)
    print(aa, number)
